<?php

namespace Okeanos\CoreBundle\Repository;

/**
 * DonatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonatesRepository extends \Doctrine\ORM\EntityRepository
{
}
